### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [ceschindler/weddingProject#1]
Hi Collin,

I'm sorry I ran out of time last night to review your indie project work to date.  You have a solid project idea here and it looks like you've thought out the technologies you'll be using. I do think Travis CI would make an excellent independent research topic if you haven't worked with it before- selfishly, because I'd like to learn more about it, but also because it's a tool everyone in class could benefit from). 

A few items seem to missing though - the documents in your repository are 0 bytes: 
- [x] Project Plan
- [x] Application flow
- [x] Screen design
- [x] Time log

**Comment by ceschindler** [comment]
I realize that the Screen design must be in the Pencil proprietary format and maybe this won't show up correctly... I can take screen shots of them and maybe upload it as a pdf or something.

**Comment by ceschindler** [comment]
Alright, I haven't extrapolated out the Project plan passed week 7 so far, but I will update it with more information when the time gets closer. Otherwise, I believe that everything else is in order! Let me know if you come up with more things to checkout/expand on!
